name: mlops-imgclass
channels:
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.3.0=h57928b3_0
  - absl-py=2.3.1=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.10.0=pyhe01879c_0
  - aom=3.9.1=he0c23c2_0
  - astunparse=1.6.3=pyhd8ed1ab_3
  - brotli=1.1.0=h2466b09_3
  - brotli-bin=1.1.0=h2466b09_3
  - brotli-python=1.1.0=py310h9e98ed7_3
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h2466b09_0
  - ca-certificates=2025.11.4=haa95532_0
  - cairo=1.16.0=he9e932c_7
  - certifi=2025.11.12=py310haa95532_0
  - cffi=1.17.1=py310ha8f682b_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.2.1=pyh7428d3b_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py310hc19bc0b_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=hcfcfb64_0
  - dnspython=2.7.0=pyhff2d567_1
  - email-validator=2.2.0=pyhd8ed1ab_1
  - email_validator=2.2.0=hd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - expat=2.7.1=h8ddb27b_0
  - fastapi=0.116.1=h26c32bb_1
  - fastapi-cli=0.0.8=pyhd8ed1ab_0
  - fastapi-core=0.116.1=pyhe01879c_1
  - fontconfig=2.14.1=hb33846d_3
  - fonttools=4.59.1=py310hdb0e946_0
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.13.3=h0620614_0
  - fribidi=1.0.10=h8d14728_0
  - gast=0.6.0=pyhd8ed1ab_0
  - giflib=5.2.2=h64bf75a_0
  - google-pasta=0.2.0=pyhd8ed1ab_2
  - graphite2=1.3.14=hac47afa_2
  - greenlet=3.2.4=py310h73ae2b4_0
  - grpcio=1.71.0=py310hbb1fe6b_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.2.0=pyhd8ed1ab_0
  - h5py=3.14.0=py310h6fc9867_0
  - harfbuzz=10.2.0=he2f9f60_1
  - hdf5=1.14.5=ha36df97_2
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httptools=0.6.4=py310ha8f682b_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.2=h63175ca_0
  - idna=3.10=pyhd8ed1ab_1
  - impi_rt=2021.14.1=h57928b3_13
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - jpeg=9e=hcfcfb64_3
  - keras=3.11.2=pyh753f3f9_0
  - kiwisolver=1.4.9=py310h1e1005b_0
  - lcms2=2.16=h62be587_1
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250127.0=cxx17_h4eb7d71_0
  - libavif=1.3.0=hf2698fe_0
  - libavif16=1.3.0=hf2698fe_0
  - libblas=3.9.0=34_h5709861_mkl
  - libbrotlicommon=1.1.0=h2466b09_3
  - libbrotlidec=1.1.0=h2466b09_3
  - libbrotlienc=1.1.0=h2466b09_3
  - libcblas=3.9.0=34_h2a3cdd5_mkl
  - libclang13=14.0.6=default_h8e68704_2
  - libcurl=8.14.1=h2300eb9_1
  - libdeflate=1.22=h2466b09_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.2=h405b238_0
  - libgrpc=1.71.0=hf4237ab_0
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libkrb5=1.21.3=h885b0b7_4
  - liblapack=3.9.0=34_hf9ab0e9_mkl
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.4=h4a159e6_2
  - libprotobuf=5.29.3=h65a231f_1
  - libre2-11=2024.07.02=hd248061_3
  - libssh2=1.11.1=h2addb87_0
  - libtiff=4.7.0=h404307b_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxml2=2.13.8=h866ff63_0
  - libxslt=1.1.43=h25c3957_0
  - llvm-openmp=20.1.8=hfa2b4ca_1
  - lz4-c=1.9.4=hcfcfb64_0
  - markdown=3.8.2=pyhd8ed1ab_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.2=py310h38315fa_1
  - matplotlib=3.10.1=py310h5588dad_0
  - matplotlib-base=3.10.1=py310h37e0a56_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - minizip=4.0.3=hb68bac4_0
  - mkl=2024.2.2=h57928b3_16
  - ml_dtypes=0.5.1=py310hb4db72f_0
  - mpi=1.0=impi
  - mpi4py=4.1.0=py310h4919421_101
  - munkres=1.1.4=pyhd8ed1ab_1
  - namex=0.1.0=pyhd8ed1ab_0
  - numpy=2.0.2=py310h1ec8c79_1
  - openjpeg=2.5.2=h9b5d1b5_1
  - openssl=3.5.2=h725018a_0
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - optree=0.17.0=py310he9f1925_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.1=py310hed136d8_0
  - pcre2=10.42=h0ff8eda_1
  - pillow=11.3.0=py310hb328d1f_0
  - pip=25.1=pyhc872135_2
  - pixman=0.46.4=h5112557_1
  - protobuf=5.29.3=py310h9e98ed7_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.7=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py310hed05c55_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhe01879c_2
  - pyside6=6.7.3=py310h28b127d_1
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.10.18=h981015d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.1.1=pyhe01879c_0
  - python-flatbuffers=25.2.10=pyhbc23db3_0
  - python-multipart=0.0.20=pyhff2d567_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py310h38315fa_2
  - qhull=2020.2=hc790b64_5
  - qtbase=6.7.3=hd088775_4
  - qtdeclarative=6.7.3=h885b0b7_1
  - qtshadertools=6.7.3=h885b0b7_1
  - qtsvg=6.7.3=h9d4b640_1
  - qttools=6.7.3=hcb596f7_1
  - qtwebchannel=6.7.3=h885b0b7_1
  - qtwebengine=6.7.3=h3869032_1
  - qtwebsockets=6.7.3=h885b0b7_1
  - rav1e=0.7.1=ha073cba_3
  - re2=2024.07.02=haf4117d_3
  - requests=2.32.5=pyhd8ed1ab_0
  - rich=14.1.0=pyhe01879c_0
  - rich-toolkit=0.15.0=pyhe01879c_0
  - scikit-learn=1.7.1=py310h21054b0_0
  - scipy=1.15.2=py310h15c175c_0
  - seaborn=0.13.2=py310haa95532_3
  - setuptools=78.1.1=py310haa95532_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - sqlalchemy=2.0.43=py310h29418f3_0
  - sqlite=3.50.2=hda9a48d_1
  - starlette=0.47.2=pyh82d4cca_0
  - svt-av1=3.0.2=he0c23c2_0
  - tbb=2021.13.0=h18a62a1_2
  - tensorboard=2.18.0=pyhd8ed1ab_1
  - tensorboard-data-server=0.7.0=py310h5588dad_2
  - tensorflow=2.18.1=cpu_py310h6605a60_0
  - tensorflow-base=2.18.1=cpu_py310h1ab519a_0
  - termcolor=3.1.0=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.2=py310h29418f3_0
  - typer=0.16.1=pyhc167863_0
  - typer-slim=0.16.1=pyhe01879c_0
  - typer-slim-standard=0.16.1=h810d63d_0
  - typing-extensions=4.14.1=h4440ef1_0
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=16.0.0=py310ha8f682b_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - uvicorn=0.35.0=pyh5737063_0
  - uvicorn-standard=0.35.0=h5737063_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - watchfiles=1.1.0=py310hc226416_0
  - websockets=15.0.1=py310h1637853_1
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=py310haa95532_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - wrapt=1.17.3=py310h29418f3_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=h6a83c73_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h8cc25b3_1
  - zstandard=0.23.0=py310ha8f682b_2
  - zstd=1.5.6=h8880b57_0
  - pip:
      - alembic==1.16.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - cloudpickle==3.1.1
      - comm==0.2.3
      - cryptography==45.0.6
      - databricks-sdk==0.64.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - docker==7.1.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - flask==3.1.2
      - fqdn==1.5.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.40.3
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - ipykernel==7.1.0
      - ipython==8.37.0
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - kaggle==1.7.4.5
      - lark==1.3.1
      - mako==1.3.10
      - matplotlib-inline==0.2.1
      - mistune==3.1.4
      - mlflow==3.3.1
      - mlflow-skinny==3.3.1
      - mlflow-tracing==3.3.1
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - onnx==1.18.0
      - opentelemetry-api==1.36.0
      - opentelemetry-sdk==1.36.0
      - opentelemetry-semantic-conventions==0.57b0
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.5
      - platformdirs==4.5.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - psutil==7.1.3
      - pure-eval==0.2.3
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - python-json-logger==4.0.0
      - python-slugify==8.0.4
      - pywin32==311
      - pywinpty==3.0.2
      - pyzmq==27.1.0
      - referencing==0.37.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.28.0
      - rsa==4.9.1
      - send2trash==1.8.3
      - smmap==5.0.2
      - soupsieve==2.8
      - sqlparse==0.5.3
      - stack-data==0.6.3
      - terminado==0.18.1
      - text-unidecode==1.3
      - tinycss2==1.4.0
      - tomli==2.2.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - uri-template==1.3.0
      - waitress==3.0.2
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
prefix: C:\Users\Aishu\miniconda3\envs\mlops-imgclass
